"""Plan types shared by every rule evaluator.

An evaluator is a pure function: (rule, workbook, scope, config, ctx) -> RulePlan.
It never mutates its input. A plan carries the complete before/after state of
each tab it touches, so that:
  * dry-run   = evaluate, then summarize (no apply)
  * executor  = evaluate, snapshot `before`, then commit `after`
share one code path (CLAUDE.md, coding conventions).
"""

from __future__ import annotations

from dataclasses import dataclass, field

from app.schemas.config import ConfigSpec
from app.services.grid import Tab, Workbook


class RuleAbort(Exception):
    """The rule cannot be applied safely; nothing from it may be applied."""


@dataclass
class TabStats:
    rows_moved: int = 0
    rows_formatted: int = 0
    rows_added: int = 0
    rows_removed: int = 0
    rows_cleared: int = 0
    cells_validated: int = 0

    @property
    def rows_affected(self) -> int:
        return max(self.rows_moved, self.rows_added, self.rows_removed, self.rows_cleared, self.rows_formatted)

    def add(self, other: TabStats) -> None:
        self.rows_moved += other.rows_moved
        self.rows_formatted += other.rows_formatted
        self.rows_added += other.rows_added
        self.rows_removed += other.rows_removed
        self.rows_cleared += other.rows_cleared
        self.cells_validated += other.cells_validated


@dataclass
class TabChange:
    tab: str
    before: Tab | None  # None = the rule creates this tab
    after: Tab
    stats: TabStats = field(default_factory=TabStats)

    @property
    def values_changed(self) -> bool:
        return self.before is None or self.before.values != self.after.values

    @property
    def changed(self) -> bool:
        b = self.before
        return (
            b is None
            or b.values != self.after.values
            or b.formats != self.after.formats
            or b.validations != self.after.validations
            or b.protected != self.after.protected
            or b.number_formats != self.after.number_formats
            or b.column_widths != self.after.column_widths
            or b.banding != self.after.banding
        )


@dataclass
class RulePlan:
    rule_id: str
    action: str
    changes: list[TabChange] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    error: str | None = None  # set when the rule aborted; `changes` is then empty
    blocked: str | None = None  # set when a guard refuses the plan

    @property
    def destructive(self) -> bool:
        return any(c.values_changed for c in self.changes)

    @property
    def rows_affected(self) -> int:
        return sum(c.stats.rows_affected for c in self.changes)

    @property
    def applicable(self) -> bool:
        return self.error is None and self.blocked is None


def apply_plan(workbook: Workbook, plan: RulePlan) -> Workbook:
    """Return a new workbook with the plan's `after` tabs swapped in (input untouched)."""
    out = workbook.clone()
    if not plan.applicable:
        return out
    for change in plan.changes:
        out.put(change.after.clone(), insert_at=0)
    return out


def config_targets(config: ConfigSpec) -> set[str]:
    """Tabs generated by consolidate rules: never treated as sources or governed data."""
    return {r.target_tab for r in config.rules if r.action == "consolidate"}
