"""s2 registry

Revision ID: 0001
Revises: 
Create Date: 2026-09-18 11:32:17.595306

S2 registry: orgs, sheets, configs, runs, snapshots (encrypted, expiring), events,
watch_state (PATCH-002 A.1), flags (schema only, PATCH-001 B).

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('snapshot_retention_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('google_sheet_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=300), server_default='', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='ACTIVE', nullable=False),
    sa.Column('active_config_id', sa.BigInteger(), nullable=True),
    sa.Column('last_fingerprint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('self_write_watermark', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sheet_id')
    )
    op.create_index(op.f('ix_sheets_org_id'), 'sheets', ['org_id'], unique=False)
    op.create_table('watch_state',
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('page_token', sa.String(length=256), nullable=False),
    sa.Column('last_purge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('sheet_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sheet_id', 'version')
    )
    op.create_index(op.f('ix_configs_org_id'), 'configs', ['org_id'], unique=False)
    op.create_index(op.f('ix_configs_sheet_id'), 'configs', ['sheet_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('sheet_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_org_id'), 'events', ['org_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('sheet_id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('rows_affected', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duration_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_org_id'), 'runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_runs_run_id'), 'runs', ['run_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('sheet_id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('tab', sa.String(length=200), nullable=False),
    sa.Column('range_a1', sa.String(length=64), nullable=False),
    sa.Column('existed', sa.Boolean(), nullable=False),
    sa.Column('body_gz', sa.LargeBinary(), nullable=True),
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_org_id'), 'snapshots', ['org_id'], unique=False)
    op.create_index(op.f('ix_snapshots_run_id'), 'snapshots', ['run_id'], unique=False)
    op.create_table('flags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('sheet_id', sa.BigInteger(), nullable=False),
    sa.Column('class', sa.String(length=1), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='OPEN', nullable=False),
    sa.Column('proposed_config_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['proposed_config_id'], ['configs.id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flags_org_id'), 'flags', ['org_id'], unique=False)
    # sheets <-> configs cycle: add after both tables exist
    op.create_foreign_key('fk_sheets_active_config', 'sheets', 'configs', ['active_config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sheets_active_config', 'sheets', type_='foreignkey')
    op.drop_index(op.f('ix_flags_org_id'), table_name='flags')
    op.drop_table('flags')
    op.drop_index(op.f('ix_snapshots_run_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_org_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_runs_run_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_org_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_events_org_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_configs_sheet_id'), table_name='configs')
    op.drop_index(op.f('ix_configs_org_id'), table_name='configs')
    op.drop_table('configs')
    op.drop_table('watch_state')
    op.drop_index(op.f('ix_sheets_org_id'), table_name='sheets')
    op.drop_table('sheets')
    op.drop_table('orgs')
    # ### end Alembic commands ###
