"""config decisions title headers source

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-18 17:37:00.411181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configs', sa.Column('rejected_by', sa.String(length=200), nullable=True))
    op.add_column('configs', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('configs', sa.Column('decision_reason', sa.Text(), nullable=True))
    op.add_column('configs', sa.Column('summary_title', sa.String(length=200), nullable=True))
    op.add_column('configs', sa.Column('governed_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('configs', sa.Column('source', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configs', 'source')
    op.drop_column('configs', 'governed_headers')
    op.drop_column('configs', 'summary_title')
    op.drop_column('configs', 'decision_reason')
    op.drop_column('configs', 'rejected_at')
    op.drop_column('configs', 'rejected_by')
    # ### end Alembic commands ###
